/** This file is part of the Lepus Framework. For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

package lepus.app

import com.google.inject.Injector

import org.http4s.{ HttpApp, Response }

/** A model for providing server configuration information. Only one must be generated by the application.
 *
 * For example:
 * {{{
 *  object HttpApp extends LepusApp[IO]:
 *    val routes = Router(
 *      "/" -> HttpRoutes.of[IO] {
 *        case GET -> Root / "hello" / name => Ok(s"Hello $name")
 *      }
 *    ).orNotFound
 * }}}
 *
 * @tparam F
 *   the effect type.
 */
trait LepusApp[F[_]]:

  /** List of all endpoints to be launched by the application */
  val routes: Injector ?=> HttpApp[F]

  /** Methods to define handling of errors that occur during application execution */
  val errorHandler: PartialFunction[Throwable, F[Response[F]]]
